# main data such as package name etc.
[tfg-kpm.main]
name = "t5additions"

# package data
[tfg-kpm.package]
recipes = ["registerCreateBigCannonsRecipes(event)"]
itemtags = ["registerCreateBigCannonsItemTags"]
blocktags = []
fluidtags = []